server:
  port: 9700
spring:
  profiles:
    active: dev
  application:
    name: zpyjdata
  aop:
    auto: true #启动aop配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai # 时间少了8个小时的问题

