server:
  servlet:
    context-path:
spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: true
      datasource:
        master:
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          url: jdbc:p6spy:mysql://47.115.217.193:3306/zpyj?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          username: root
          password: h1tc7!P((GZK)SN
#          url: jdbc:p6spy:mysql://47.115.217.193:3306/zpyj_trial?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#          username: zpyj
#          password: NMc0P}LW5F=(WZ
        miaomai:
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          url: jdbc:p6spy:mysql://47.120.17.164:3340/miaomai?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          username: root
          password: h1tc7!P((GZK)SN
          type: com.zaxxer.hikari.HikariDataSource
          hikari:
            #最大连接数，默认是 10
            maximum-pool-size: 15
            #最小空闲连接数
            minimum-idle: 5
            #连接的超时时间，默认30000 (毫秒)
            connection-timeout: 60000
            #空闲连接最大存活时间（毫秒）
            idle-timeout: 60000
            #池中连接的最长生命周期，值 0 表示无限生命周期（毫秒）
            max-lifetime: 120000
            #连接到数据库时等待最长时间(秒)
            login-timeout: 5
